project_id = "tiewnnskjyvnyqfbszev"

[functions.send-verification-email]
verify_jwt = false

[functions.verify-email-token]
verify_jwt = false

[functions.get-stripe-publishable-key]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false